version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12 # Use your desired version
        environment:
          NODE_ENV: development # Only needed if puppeteer is in `devDependencies`
    steps:
      - checkout
      - run: npm install
      - run: npm run test

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test
